version: '3'

# サービスを定義する
services:

  # PHPサービス
  php:
    build: ./php
    volumes:
      - ../app:/var/www/html/app:delegated
      - ../doc/api_reference:/var/www/html/app/public/api_reference
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - bridge-network
    hostname: php
    working_dir: /var/www/html/app
    depends_on:
      - postgres
      - minio
      - mailhog

  # NGINXサービス
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/:delegated
      - ../app:/var/www/html/app:cached
    networks:
      - bridge-network
    ports:
      - "${HOST_IP}:8000:8000"
    hostname: nginx
    depends_on:
      - php

  # Postgresサービス
  postgres:
    image: postgres:15.1
    volumes:
      - postgres-data:/var/lib/postgres:delegated
    networks:
      - bridge-network
    ports:
      - "${HOST_IP}:5432:5432"
    environment:
      POSTGRES_DB: contract
      POSTGRES_USER: user
      POSTGRES_PASSWORD: arigato39

  # テスト用Postgresサービス
  test-postgres:
    image: postgres:15.1
    volumes:
      - test-postgres-data:/var/lib/postgres:delegated
    networks:
      - bridge-network
    ports:
      - "${HOST_IP}:5433:5432"
    environment:
      POSTGRES_DB: contract
      POSTGRES_USER: user
      POSTGRES_PASSWORD: arigato39

  # Minioサービス
  minio:
    image: minio/minio:latest
    volumes:
      - minio-storage:/data
      - ./minio/bucket-policy.json:/bucket-policy.json
    networks:
      - bridge-network
    expose:
      - '9000'
    ports:
      - '${HOST_IP}:9001:9001'
    hostname: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    entrypoint: sh
    command: >
      -c "mkdir -p /data/my-bucket &&
      mkdir -p /data/.minio.sys/buckets/my-bucket && 
      cp bucket-policy.json /data/.minio.sys/buckets/my-bucket/policy.json && 
      minio server /data --console-address ':9001'
      "

  # Mailhogサービス
  mailhog:
    image: mailhog/mailhog
    networks:
      - bridge-network
    ports:
      - "${HOST_IP}:8025:8025"

# ボリュームを定義する
volumes:
  # Postgresデータ
  postgres-data:
  # テスト用Postgresデータ
  test-postgres-data:
  # MinIOストレージ
  minio-storage:

# ネットワークを定義する
networks:
  # ブリッジネットワーク
  bridge-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.101.0/24
